name: 
run-name: prepare-job-environment-for-devenv
on: workflow_dispatch
jobs:
  prepare-job-environment-for-devenv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v23
      - uses: cachix/cachix-action@v12
        with:
          name: devenv
      - name: Install devenv.sh
        run: nix profile install tarball+https://install.devenv.sh/latest
      - name: Build the devenv shell and run any pre-commit hooks
        run: devenv ci  
      - name: Run a multi-line command in the devenv shell
        shell: devenv shell bash -e {0}
        run: |
          hello
          say-bye
