on:
  push:
    branches:
      - 'demo'
      - 'dev' 
      - 'main'



jobs:
  use-devenv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v23
      - uses: cachix/cachix-action@v12
        with:
          name: devenv
      - name: Install devenv.sh
        run: nix profile install tarball+https://install.devenv.sh/latest
